repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: python3 -m isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: python3 -m black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: python3 -m mypy src
        language: system
        pass_filenames: false
